### ISSUE TITLE
Having a problem on the client

### ISSUE THREAD

**Issue by HydenLee11** [fangsong0517/Chat-Room#1]
the clients can be only running on one host，when I opened a client in another system and tried  to join the server ，it showed no response  like this.
![IMG_20230228_084549](https://user-images.githubusercontent.com/126487385/221732731-c5dd564d-be40-4c77-9d8f-478187e5337c.jpg)

**Comment by fangsong0517** [comment]
ok, try again

**Comment by fangsong0517** [comment]
> the clients can be only running on one host，when I opened a client in another system and tried to join the server ，it showed no response like this. ![IMG_20230228_084549](https://user-images.githubusercontent.com/126487385/221732731-c5dd564d-be40-4c77-9d8f-478187e5337c.jpg)

It is possible that you have not modified the ip in the configuration of the client, just modify it to your local ip.
